keys:
  # right-click opens the item price dialog in PoE2
  rightclick_key: 'f3'
  # calculate the discounted price and pastes it into the dialog
  calcprice_key: 'f4'
  # exit the program
  exit_key: 'f5'
logic:
  # factor to multiply the current price by to get the new discounted price
  adjustment_factor: 0.9
currency:
  # autoupdate currency values, or set them manually
  autoupdate: true
  # the game to get currency values for, '1' or '2'
  game: 2
  # the PoE1/PoE2 league to get currency values for
  league: 'Rise of the Abyssal'